services:
  app:
    image: dunglas/frankenphp
    volumes:
      - ./:/app
      - ../src/agent:/src/agent
      - ../src/ai-bundle:/src/ai-bundle
      - ../src/platform:/src/platform
      - ../src/store:/src/store
    ports:
      - 443:443
    tty: true

  composer:
    image: composer:latest
    volumes:
      - ./:/app
      - ../src/agent:/src/agent
      - ../src/ai-bundle:/src/ai-bundle
      - ../src/platform:/src/platform
      - ../src/store:/src/store

  chromadb:
    image: chromadb/chroma:0.5.23
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
