<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Tests\E2E;

/**
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class CropTest extends E2ETestCase
{
    public function testImageIsCroppedOnItsRelevantArea()
    {
        $this->client->request('GET', '/crop');
        $this->client->waitForVisibility('#crop-component');

        // Instead of uploading an image, one of the demo images shipped with the app is used.
        $this->click('button[data-live-action-param="selectPreset"]');
        $this->client->waitForVisibility('button.btn-primary:not([disabled])');

        $this->click('button.btn-primary');
        $this->waitForElementCount('img[alt="Cropped Image"]', 1);

        $this->assertSelectorExists('img[alt="Original Image"]');
        $this->assertSelectorTextContains('#chat-body', 'Cropped Image');

        // The cropped image is rendered as data URL, generated by GD based on the detected area.
        $cropped = $this->crawler()->filter('img[alt="Cropped Image"]')->attr('src');
        $this->assertStringStartsWith('data:image/', (string) $cropped);

        $panel = $this->openAiPanel();

        // Object detection runs on Hugging Face, and does not report any token usage.
        $panel->assertMetrics(platformCalls: 1, toolCalls: 0);
        $panel->assertPlatformCall('facebook/detr-resnet-50', tokenUsage: false);
    }

    protected function requiredApiKeys(): array
    {
        return ['HUGGINGFACE_API_KEY'];
    }
}
